# Numpy

In [ ]:
import numpy as np

## 1. Create a numpy array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
listy = [1, 2, 3, 4, 5]
type(listy)

list

In [ ]:
listy_np = np.array(listy)
listy_np

array([1, 2, 3, 4, 5])

In [ ]:
type(listy_np)

numpy.ndarray

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.shape

(4, 3)

In [ ]:
arr.dtype # type of elements

dtype('int64')

In [ ]:
arr.size # number of elements

12

In [ ]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0, 4, 5)

array([0., 1., 2., 3., 4.])

## 2. Operations

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [ ]:
arr1 + arr2

array([5, 7, 9])

In [ ]:
arr1 * arr2

array([ 4, 10, 18])

In [ ]:
10 * arr1

array([10, 20, 30])

In [ ]:
arr2 / arr1

array([4. , 2.5, 2. ])

In [ ]:
arr1 ** 2

array([1, 4, 9])

## 3. Time comparison

In [ ]:
import time

python_list = list(range(10000000))
start = time.time()
python_result = [x ** 3 for x in python_list]
print("Python list time:", time.time() - start)

numpy_array = np.arange(100000000)
start = time.time()
numpy_result = numpy_array ** 3
print("NumPy array time:", time.time() - start)

Python list time: 3.66874623298645
NumPy array time: 0.4551379680633545
